create table if not exists public.patients (
    id integer generated by default as identity (start with 101) primary key,
    name varchar(50) not null,
    age integer not null check (age between 1 and 119),
    disease varchar(50) not null,
    severity integer not null check (severity between 1 and 3),
    created_at timestamptz not null default now()
);

create table if not exists public.doctors (
    id bigint generated by default as identity primary key,
    name varchar(50) not null,
    department varchar(50) not null,
    patients_treated integer not null default 0 check (patients_treated >= 0),
    unique (name, department)
);

create table if not exists public.treatment_queue (
    patient_id integer primary key references public.patients(id) on delete cascade,
    queued_at timestamptz not null default now()
);

create table if not exists public.discharge_history (
    history_id bigint generated always as identity primary key,
    patient_id integer not null,
    name varchar(50) not null,
    age integer not null,
    disease varchar(50) not null,
    severity integer not null,
    discharged_at timestamptz not null default now()
);

insert into public.doctors (name, department) values
    ('Dr. Sharma', 'General Medicine'),
    ('Dr. Patil', 'General Medicine'),
    ('Dr. Rao', 'Cardiology'),
    ('Dr. Khan', 'Orthopedics'),
    ('Dr. Mehta', 'Orthopedics'),
    ('Dr. Nair', 'Dermatology')
on conflict (name, department) do nothing;

alter table public.patients enable row level security;
alter table public.doctors enable row level security;
alter table public.treatment_queue enable row level security;
alter table public.discharge_history enable row level security;

revoke all on public.patients from public, anon;
revoke all on public.doctors from public, anon;
revoke all on public.treatment_queue from public, anon;
revoke all on public.discharge_history from public, anon;
revoke all on all sequences in schema public from public, anon;

drop policy if exists "Staff can manage patients" on public.patients;
create policy "Staff can manage patients"
    on public.patients for all to authenticated
    using (true) with check (true);

drop policy if exists "Staff can view doctors" on public.doctors;
create policy "Staff can view doctors"
    on public.doctors for select to authenticated using (true);

drop policy if exists "Staff can update doctor workloads" on public.doctors;
create policy "Staff can update doctor workloads"
    on public.doctors for update to authenticated
    using (true) with check (true);

drop policy if exists "Staff can manage treatment queue" on public.treatment_queue;
create policy "Staff can manage treatment queue"
    on public.treatment_queue for all to authenticated
    using (true) with check (true);

drop policy if exists "Staff can view discharge history" on public.discharge_history;
create policy "Staff can view discharge history"
    on public.discharge_history for select to authenticated using (true);

drop policy if exists "Staff can add discharge history" on public.discharge_history;
create policy "Staff can add discharge history"
    on public.discharge_history for insert to authenticated with check (true);

drop policy if exists "Staff can delete discharge history" on public.discharge_history;
create policy "Staff can delete discharge history"
    on public.discharge_history for delete to authenticated using (true);

grant select, insert, update, delete on public.patients to authenticated;
grant select, update on public.doctors to authenticated;
grant select, insert, delete on public.treatment_queue to authenticated;
grant select, insert, delete on public.discharge_history to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace function public.treat_next_patient()
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
    patient_row public.patients%rowtype;
    doctor_row public.doctors%rowtype;
    target_department text;
begin
    select p.*
    into patient_row
    from public.treatment_queue q
    join public.patients p on p.id = q.patient_id
    order by p.severity, q.queued_at, p.id
    limit 1
    for update of p;

    if not found then
        raise exception 'There are no patients waiting in the queue.';
    end if;

    target_department := case
        when lower(patient_row.disease) like '%heart%'
          or lower(patient_row.disease) like '%chest%'
          or lower(patient_row.disease) like '%bp%'
            then 'Cardiology'
        when lower(patient_row.disease) like '%fracture%'
          or lower(patient_row.disease) like '%bone%'
          or lower(patient_row.disease) like '%accident%'
            then 'Orthopedics'
        when lower(patient_row.disease) like '%skin%'
          or lower(patient_row.disease) like '%rash%'
          or lower(patient_row.disease) like '%allergy%'
            then 'Dermatology'
        else 'General Medicine'
    end;

    select d.*
    into doctor_row
    from public.doctors d
    where d.department = target_department
    order by d.patients_treated, d.id
    limit 1
    for update;

    if not found and target_department <> 'General Medicine' then
        select d.*
        into doctor_row
        from public.doctors d
        where d.department = 'General Medicine'
        order by d.patients_treated, d.id
        limit 1
        for update;
    end if;

    if not found then
        raise exception 'No doctor is available to treat this patient.';
    end if;

    update public.doctors
    set patients_treated = patients_treated + 1
    where id = doctor_row.id;

    delete from public.treatment_queue where patient_id = patient_row.id;

    return jsonb_build_object(
        'patient_id', patient_row.id,
        'patient_name', patient_row.name,
        'doctor_name', doctor_row.name,
        'department', doctor_row.department
    );
end;
$$;

create or replace function public.discharge_patient(p_patient_id integer)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
    patient_row public.patients%rowtype;
begin
    select p.* into patient_row
    from public.patients p
    where p.id = p_patient_id
    for update;

    if not found then
        raise exception 'Patient not found.';
    end if;

    insert into public.discharge_history (patient_id, name, age, disease, severity)
    values (patient_row.id, patient_row.name, patient_row.age, patient_row.disease, patient_row.severity);

    delete from public.treatment_queue where patient_id = patient_row.id;
    delete from public.patients where id = patient_row.id;
end;
$$;

create or replace function public.undo_last_discharge()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
    history_row public.discharge_history%rowtype;
begin
    select h.* into history_row
    from public.discharge_history h
    order by h.history_id desc
    limit 1
    for update;

    if not found then
        raise exception 'There is no discharge to undo.';
    end if;

    insert into public.patients (id, name, age, disease, severity)
    values (history_row.patient_id, history_row.name, history_row.age, history_row.disease, history_row.severity);

    delete from public.discharge_history where history_id = history_row.history_id;
end;
$$;

revoke execute on function public.treat_next_patient() from public, anon;
revoke execute on function public.discharge_patient(integer) from public, anon;
revoke execute on function public.undo_last_discharge() from public, anon;
grant execute on function public.treat_next_patient() to authenticated;
grant execute on function public.discharge_patient(integer) to authenticated;
grant execute on function public.undo_last_discharge() to authenticated;
