server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/hospital_management?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${HOSPITAL_DB_USER:root}
spring.datasource.password=${HOSPITAL_DB_PASSWORD:}

spring.sql.init.mode=always
spring.thymeleaf.cache=true
